shop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

shop/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),
]

shop/shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'
urlpatterns = [
    path('', views.AllProdCat, name='AllProdCat'),
    path('<slug:c_slug>/', views.AllProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProDetail, name='prodCatdetail'),

]

shop/cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shop/search_app/models.py
from django.db import models

# Create your models here.

shop/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])



    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'


    def __str__(self):
        return '{}'.format(self.name)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shop/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q (desc__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

shop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def AllProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,2)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})


def ProDetail(request,c_slug,product_slug):
    try:
        product= Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'pro.html',{'product': product})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <meta name="description"content="{% block metadescription %}{% endblock %}">

    <title>{% block tittle %}{% endblock %}</title>
</head>

<body>
<div>
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/boostrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"> </script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      This is ur cart
{% endblock %}
{% block tittle %}
   Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div>
        <br>
        <h1 class="text-center my_tittle">
            Your shoping cart is empty
        </h1>
        <br> q121
        <p class="text-center">Please click  <a href="{% url 'shop:AllProdCat' %}">Here to continue</a></p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">Your shopping cart</h1>
        <br>
    </div>
    <div class="row-mx-auto">
        <div class="col-12 col-sm12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your items
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" alt="image" width="100" height="100"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                         {{cart_item.product.id}}
                        <br>
                         {{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x {{cart_item}}
                    </td>
                    <td>
                        {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                      <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                      </td>
                    {% endif %}
                </tr>
            {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
<div class="col-12 col-sm-12 col-sd-12 col-lg-6 text=center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review shiping cart items before with payment process
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your total amount to pay:<strong>{{ total }}</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'shop:AllProdCat' %}" class="btn btn-secondary btn-block my_custom_button"> Continue shoping</a>
    </div>
</div>
</div>
{% endif %}

{% endblock %}

shop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
     {{category.desc|truncatewords:155}}
  {% else %}
      Welcome to E Cart everything u want...
  {% endif %}
{% endblock %}
{% block tittle %}
  {% if category %}
     {{ category.name }}-E cart
  {% else %}
      U can c our new products
  {% endif %}
{% endblock %}
{% block content %}
  {% if category %}

     <div>
         <div class="row my_row_class" >
             <div class="mx-auto">
             <p><a href="{% url 'shop:AllProdCat' %}">Our Products</a></p>
         </div>
             </div>
     </div>
     {% endif %}
<div class="mx_auto">
    {% if category %}
      <img class="my_img" src="{{category.img.url}}" alt="{{category.name}}" width="200" height="200">
</div>
    <br>
<div>
      <h1 class="text-center my_tittle">{{category.name}}</h1>
      <p class="text-justify">{{category.desc}}</p>
</div>
     {% else %}
<div>
        <img class="my_img my_img_padding" src="{% static 'img/banner.png' %}" alt="our products" width="200" height="200" >
</div>
<br>
<div>
    <h1 class="text-center my_tittle">our products collections</h1>
    <p class="text-justify"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
</div>
      {% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18;">
                <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.img.url}}" alt="{{product.name}}" width="200" height="200"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <h4>{{product.price}}</h4>

            </div>
            </div>
        </div>

        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class ="text-center">&copy E- Cart tech pvt limited all rights Reserved</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'shop:AllProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage"  width="120" height="140">
    </center>
</header>

shop/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}"> {{cat.name}} </a></li>

            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
        </li>
        {% endif %}
      </ul>
      <div class="class=col-md-12 col-sm12">
        <div>
          <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
            <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
        </div>
      </div>
    </div>
  </div>
</nav>

shop/templates/pro.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{product.desc|truncatewords:155}}
{% endblock %}
{% block tittle %}
  {% if category %}
     {{ product.name }}-E cart
  {% endif %}
{% endblock %}
{% block content%}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:AllProdCat' %}">Home</a> | <a href="{{product.category.get_url}}"></a>| {{product.category}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}" width="200" height="500">
        </div>
    </div>

        <div class="col-12 cl-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_tittle">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_tittle">Product description</p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
            <p>{{product.stock}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
</div>
</div>
</div>

{% endblock %}

shop/templates/sampl.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:AllProdCat' %}">All products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}"> {{cat.name}}</a></li>

            {% endfor %}}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Your cart</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>





<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Your cart</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="{% url 'shop:AllProdCat' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">


              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}"> {{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>


<nav>
  <ul>
    <li><a href="{% url 'shop:AllProdCat' %}">All products</a></li>
    {% for cat in links %}
    <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>
    {% endfor %}
    <li>Your cart</li>
  </ul>
</nav>

shop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
      Welcome to E Cart everything u want...
{% endblock %}
{% block tittle %}
   search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have saerched for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18;">
                <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.img.url}}" alt="{{product.name}}" width="200" height="200"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <h4>{{product.price}}</h4>

            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="tect_center ,my_search-text"> 0 result found</p>
        </div>
    </div>
        {% endfor %}
   </div>

{% endblock %}